"""Update User

Revision ID: 3d88ba222821
Revises: 561470d3cc84
Create Date: 2022-04-26 20:19:39.090450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d88ba222821'
down_revision = '561470d3cc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients_purchase', 'purchase_quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.alter_column('production_recipes', 'recipe_quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.drop_column('users', 'creation_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('creation_date', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('production_recipes', 'recipe_quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ingredients_purchase', 'purchase_quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
