"""Change User

Revision ID: 561470d3cc84
Revises: f35c0404c392
Create Date: 2022-04-26 16:04:40.295572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561470d3cc84'
down_revision = 'f35c0404c392'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredients_purchase', 'purchase_quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.alter_column('production_recipes', 'recipe_quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('creation_date', sa.String(), nullable=False))
    op.drop_constraint('users_user_name_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'user_name')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('user_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_user_name_key', 'users', ['user_name'])
    op.drop_column('users', 'creation_date')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    op.drop_column('users', 'name')
    op.alter_column('recipe_ingredients', 'quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('production_recipes', 'recipe_quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ingredients_purchase', 'purchase_quantity',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    # ### end Alembic commands ###
