"""tabelas2 ok

Revision ID: 61d644e63850
Revises: ee6b2d7e08bb
Create Date: 2022-04-21 19:33:06.061857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61d644e63850'
down_revision = 'ee6b2d7e08bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients_purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('purchase_quantity', sa.Float(precision=3), nullable=False),
    sa.Column('purchase_price', sa.Numeric(asdecimal=False), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.purchase_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('recipe_quantity', sa.Float(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['production_id'], ['productions.production_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(precision=3), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.ingredient_id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.recipe_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredients')
    op.drop_table('production_recipes')
    op.drop_table('ingredients_purchase')
    # ### end Alembic commands ###
